name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: 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
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
          
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          
          echo "\n## Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md
          
          cml-publish feature_importance.png --md >> report.md
          
          cml-send-comment report.md
