name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
#           ref: ${{ github.event.workflow_run.head_sha }}
            ref: "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"
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.5'
      - name: Train model
        env:
#           repo_token: ${{ secrets.GITHUB_TOKEN }}
          repo_token: "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"
        run: |
          pip3 install -r requirements.txt
          python train.py
          
          cat metrics.txt >> report.md
          echo '![](./feature_importance.png "Feature Importance")' >> report.md
          echo '![](./residuals.png "Residuals")' >> report.md
          
          echo "## Data viz" >> report.md
          cml comment create report.md
