name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
#         with:
#           ref: "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"
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.5'
      - name: Train model
        env:
          repo_token: "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"
        run: |
          pip3 install -r requirements.txt
          python train.py
          
          cat metrics.txt >> report.md
          echo '![](./feature_importance.png "Feature Importance")' >> report.md
          echo '![](./residuals.png "Residuals")' >> report.md
          
          echo "## Data viz" >> report.md
          cml comment create report.md
