name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
#         with:
#           ref: ${{ "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" }}
#       - uses: iterative/setup-cml@v1
#       - uses: actions/setup-python@v2
#         with:
#           python-version: '3.5'
      - name: Train model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          python train.py
          
          cat metrics.txt >> report.md
          echo '![](./feature_importance.png "Feature Importance")' >> report.md
          echo '![](./residuals.png "Residuals")' >> report.md
          
          echo "## Data viz" >> report.md
          cml comment create report.md
