name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
          
          cat metrics.txt >> report.md
          echo '![](./feature_importance.png --md "Feature Importance")' >> report.md
          echo '![](./residuals.png --md "Residuals")' >> report.md
          
          echo "## Data viz" >> report.md
          cml comment create report.md
